name: Build PDF Documentation

on:
#  pull_request:
  push:
    branches: [master]
#  release:
#    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        sudo apt update
        sudo apt install python3-sphinx
        sudo apt install texlive-base
        sudo apt install latexmk
    - name: Build
      run: |
        cd docmake
        latexpdf
        ls -alh
